services:
  - type: web
    name: cableops-api
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm run start:api
    envVars:
      - key: PORT
        value: 4000
      - key: CORS_ORIGIN
        value: https://cableops-web.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 12h

  - type: web
    name: cableops-web
    runtime: static
    rootDir: apps/web
    buildCommand: ""
    staticPublishPath: .
